# Generated by Django 6.0.5 on 2026-06-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Bharatnatyam', 'Bharatnatyam'), ('Kuchipudi', 'Kuchipudi'), ('Mohiniyattam', 'Mohiniyattam')], max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('sizes', models.CharField(max_length=200)),
            ],
        ),
    ]
