# Generated by Django 6.0.5 on 2026-06-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Bharatnatyam', 'Bharatnatyam'), ('Kuchipudi', 'Kuchipudi'), ('Mohiniyattam', 'Mohiniyattam'), ('Jewellery', 'Jewellery'), ('Antique Jewellery', 'Antique Jewellery'), ('Hair & Floral', 'Hair & Floral Accessories')], max_length=50),
        ),
    ]
